query ShopItem($slug: String!) {
  shopItemBySlug(slug: $slug) {
    id
    created_at
    updated_at
    name
    description
    image {
      url
      width
      height
    }
    price
    subDiscount
    giveDiscount
    type
    slug
  }
}