query Tag($tag: String!) {
    tags(where: { name: $tag }) {
        name
        blogPosts(sort: "created_at:desc") {
            id
            created_at
            title
            excerpt
            image {
                url
            }
            tags {
                name
            }
            slug
        }
    }
}