query BlogPost($slug: String!) {
    blogPostBySlug(slug: $slug) {
        id
        created_at
        updated_at
        published_at
        title
        content
        excerpt
        image {
            url
            width
            height
        }
        tags {
            name
        }
        slug
        previous {
            title
            slug
        }
        next {
            title
            slug
        }
    }
}