query BlogPosts($start: Int, $limit: Int) {
    blogPosts(sort: "published_at:desc", start: $start, limit: $limit) {
        created_at
        updated_at
        published_at
        title
        content
        excerpt
        image {
            url
            width
            height
        }
        tags {
            name
        }
        slug
    }
    blogPostsConnection {
        aggregate {
            count
        }
    }
}