query BlogPosts($slug: String!) {
    blogPostBySlug(slug: $slug) {
        id
        created_at
        updated_at
        title
        content
        excerpt
        image {
            url
            width
            height
        }
        tags {
            name
        }
        slug
    }
}