query Slides {
    slides {
        id
        image {
            url
        }
        title
        text
        buttons {
            id
            link
            text
            color
            icon
        }
    }
}